from pathlib import Path
from .scanner import ScanResult
from .ui import SimSelection

MAKEFILE_NAME = "sim_run.mk"


def generate(root: Path, scan: ScanResult, selection: SimSelection) -> Path:
    sim_dir = root / "sim"
    sim_dir.mkdir(exist_ok=True)

    makefile_path = sim_dir / MAKEFILE_NAME
    content = _render(scan, selection, root)   # pass root here
    makefile_path.write_text(content, encoding="utf-8")

    return makefile_path


def _render(scan: ScanResult, selection: SimSelection, root: Path) -> str:
    vhdl_sources = "\n".join(
        f"VHDL_SOURCES += {d.resolve()}/*.vhd"
        for d in scan.source_dirs
    )

    tb_module  = selection.testbench.stem
    test_dir   = (root / "test").resolve()

    return f"""\
# Auto-generated by vhdl-sim — do not edit by hand

# simulator
SIM                    ?= ghdl
TOPLEVEL_LANG          ?= vhdl

# VHDL standard
EXTRA_ARGS             += --std=08

# design under test
TOPLEVEL               := {selection.entity.name}
ARCH                   := {selection.architecture.name}

# timing
COCOTB_HDL_TIMEPRECISION = 1fs

# sources (one glob per discovered directory)
{vhdl_sources}

# waveform output
SIM_ARGS               += --wave=$(TOPLEVEL).ghw

# testbench
COCOTB_TEST_MODULES    := {tb_module}
export PYTHONPATH      := {selection.testbench.parent.resolve()}

# cocotb rules
include $(shell cocotb-config --makefiles)/Makefile.sim

# extended clean
clean::
\t-@rm -f $(TOPLEVEL)
\t-@rm -f e~$(TOPLEVEL).o
"""